spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
server.port = ${PORT:10000}
server.address=0.0.0.0
spring.main.lazy-initialization=true

spring.mvc.view.prefix: /WEB-INF/jsp/
spring.mvc.view.suffix: .jsp

hostDomainUrl = https://www.adcapitalinvestment.com/
spring.main.allow-bean-definition-overriding=true



admin_name = A D Capital Investment
admin_mobile = 9538363832
admin_email = connect@adcapitalinvestment.com
support_name = A D Capital Investment
support_email = connect@adcapitalinvestment.com
mail_support_name = A D Capital Investment
mail_support_email = connect@adcapitalinvestment.com







#097475